export const DATA_ROOT = "../geoinfo";

export const LAYER_GROUPS = [
  {
    id: "substations-operation",
    label: "In operation",
    section: "Substations",
    color: "#0fa3b1",
    defaultVisible: true,
    geometry: "point",
    popupPriorityFields: ["Nome", "Tensao", "Ano_Opera", "Concession"],
    fieldAliases: {
      Nome: "Substation",
      Tensao: "Voltage level",
      Ano_Opera: "Operation year",
      Concession: "Concession",
    },
    files: ["Electrical_Substation_-_in_operation"],
  },
  {
    id: "substations-planned",
    label: "Planned",
    section: "Substations",
    color: "#a855f7",
    defaultVisible: false,
    geometry: "point",
    popupPriorityFields: ["Nome", "Tensao", "Ano_Opera", "Concession"],
    fieldAliases: {
      Nome: "Substation",
      Tensao: "Voltage level",
      Ano_Opera: "Operation year",
      Concession: "Concession",
    },
    files: ["Electrical_Substation_-_Planned"],
  },
  {
    id: "transmission-operation",
    label: "In operation",
    section: "Transmission lines",
    color: "#2b7a78",
    defaultVisible: false,
    geometry: "line",
    files: ["Transmission_Line_-_in_operation"],
  },
  {
    id: "transmission-planned",
    label: "Planned",
    section: "Transmission lines",
    color: "#db6f2b",
    defaultVisible: false,
    geometry: "line",
    files: ["Transmission_Line_-_Planned"],
  },
  {
    id: "regions-sin",
    label: "Brazilian regions (SIN)",
    section: "Regions",
    color: "#5e81ac",
    defaultVisible: false,
    geometry: "polygon",
    thematicField: "reg_geog",
    thematicPalette: ["#f94144", "#f3722c", "#f9c74f", "#43aa8b", "#47769f"],
    popupPriorityFields: ["Nome", "UF", "reg_geog", "subsistee"],
    fieldAliases: {
      Nome: "State",
      UF: "UF",
      reg_geog: "Geographic region",
      subsistee: "SIN subsystem",
    },
    files: ["Subsystem_of_National_Interconnected_System_(SIN)"],
  },
  {
    id: "regions-isolated-systems",
    label: "Isolated systems",
    section: "Regions",
    color: "#8e44ad",
    defaultVisible: false,
    geometry: "point",
    popupPriorityFields: ["localidade", "uf", "municipio", "programa", "demanda", "carga"],
    fieldAliases: {
      localidade: "Location",
      uf: "UF",
      municipio: "Municipality",
      programa: "Program",
      demanda: "Demand",
      carga: "Load",
    },
    files: ["Isolated_Systems"],
  },
  {
    id: "plants-biomass-existing",
    label: "Biomass",
    section: "Power plants",
    color: "#3f8f2f",
    defaultVisible: false,
    geometry: "point",
    files: ["Biomass_Thermoelectric_-_Existing_Power_Plants"],
  },
  {
    id: "plants-biomass-planned",
    label: "Biomass",
    section: "Power plants",
    color: "#7aba52",
    defaultVisible: false,
    geometry: "point",
    files: ["Biomass_Thermoelectric_-_Planned_Power_Plants"],
  },
  {
    id: "plants-solar-existing",
    label: "Solar photovoltaic",
    section: "Power plants",
    color: "#f2b705",
    defaultVisible: false,
    geometry: "point",
    files: ["Photovoltaic_-_Existing_Power_Plants"],
  },
  {
    id: "plants-solar-planned",
    label: "Solar photovoltaic",
    section: "Power plants",
    color: "#ffd866",
    defaultVisible: false,
    geometry: "point",
    files: ["Photovoltaic_-_Planned_Power_Plants"],
  },
  {
    id: "plants-wind-existing",
    label: "Wind",
    section: "Power plants",
    color: "#1d7db8",
    defaultVisible: false,
    geometry: "point",
    files: ["Wind_-_Existing_Power_Plants"],
  },
  {
    id: "plants-wind-planned",
    label: "Wind",
    section: "Power plants",
    color: "#62b0e3",
    defaultVisible: false,
    geometry: "point",
    files: ["Wind_-_Planned_Power_Plants"],
  },
  {
    id: "plants-hydroelectric-existing",
    label: "Hydroelectric",
    section: "Power plants",
    color: "#177e89",
    defaultVisible: false,
    geometry: "point",
    files: ["Hydroelectric_-_Existing_Power_Plants"],
  },
  {
    id: "plants-hydroelectric-planned",
    label: "Hydroelectric",
    section: "Power plants",
    color: "#4fb8c4",
    defaultVisible: false,
    geometry: "point",
    files: ["Hydroeletric_-_Planned_Power_Plants"],
  },
  {
    id: "plants-small-hydro-existing",
    label: "Small hydro",
    section: "Power plants",
    color: "#2a9d8f",
    defaultVisible: false,
    geometry: "point",
    files: ["Small_Hydroelectric_-_Existing_Power_Plants"],
  },
  {
    id: "plants-small-hydro-planned",
    label: "Small hydro",
    section: "Power plants",
    color: "#7ecfb8",
    defaultVisible: false,
    geometry: "point",
    files: ["Small_Hydroelectric_-_Planned_Power_Plants"],
  },
  {
    id: "plants-micro-hydro-existing",
    label: "Micro hydro",
    section: "Power plants",
    color: "#4a8f7a",
    defaultVisible: false,
    geometry: "point",
    files: ["Micro_Hydroelectric_-_Existing_Power_Plants"],
  },
  {
    id: "plants-micro-hydro-planned",
    label: "Micro hydro",
    section: "Power plants",
    color: "#8ac6a9",
    defaultVisible: false,
    geometry: "point",
    files: ["Micro_Hydroelectric_-_Planned_Power_Plants"],
  },
  {
    id: "plants-fossil-existing",
    label: "Fossil thermoelectric",
    section: "Power plants",
    color: "#9b5f3f",
    defaultVisible: false,
    geometry: "point",
    files: ["Fossil_Thermoelectric_-_Existing_Power_Plants"],
  },
  {
    id: "plants-fossil-planned",
    label: "Fossil thermoelectric",
    section: "Power plants",
    color: "#d38f6e",
    defaultVisible: false,
    geometry: "point",
    files: ["Fossil_Thermoelectric_-_Planned_Power_Plants"],
  },
  {
    id: "plants-nuclear-existing",
    label: "Nuclear thermoelectric",
    section: "Power plants",
    color: "#845ec2",
    defaultVisible: false,
    geometry: "point",
    files: ["Nuclear_Thermoelectric_-_Existing_Power_Plants"],
  },
  {
    id: "plants-nuclear-planned",
    label: "Nuclear thermoelectric",
    section: "Power plants",
    color: "#b39ddb",
    defaultVisible: false,
    geometry: "point",
    files: ["Nuclear_Thermoelectric_-_Planned_Power_Plants"],
  },
  {
    id: "plants-biodiesel-existing",
    label: "Biodiesel",
    section: "Power plants",
    color: "#b56576",
    defaultVisible: false,
    geometry: "point",
    files: ["Biodiesel_plants"],
  },
  {
    id: "plants-biomethane-existing",
    label: "Biomethane",
    section: "Power plants",
    color: "#6d597a",
    defaultVisible: false,
    geometry: "point",
    files: ["Biomethane_plants"],
  },
  {
    id: "plants-ethanol-existing",
    label: "Ethanol",
    section: "Power plants",
    color: "#e07a5f",
    defaultVisible: false,
    geometry: "point",
    files: ["Ethanol_plants"],
  },
];
